
spring:
  redis:
    host: 47.98.137.227
    password: winsonxu_93
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
    timeout: 0ms
    database: 0

  profiles:
    active: prod
server:
  port: 8088

